### ISSUE TITLE
PDF receipt generation is failing

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#1439]
PDF receipt generation is failing and it appears to be affecting other web connections when it does.

<details>

```
website-app-1  | 2024-04-19 15:14:54,013 main         ERROR    70 russ@garrett.co.uk Unhandled exception in request: <Request 'https://www.emfcamp.org/payment/1/receipt.pdf' [GET]>
website-app-1  | Traceback (most recent call last):
website-app-1  |   File "/root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.11/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
website-app-1  |     rv = self.dispatch_request()
website-app-1  |          ^^^^^^^^^^^^^^^^^^^^^^^
website-app-1  |   File "/root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.11/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
website-app-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
website-app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
website-app-1  |   File "/root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.11/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
website-app-1  |     return current_app.ensure_sync(func)(*args, **kwargs)
website-app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
website-app-1  |   File "/app/apps/payments/invoice.py", line 124, in invoice
website-app-1  |     render_pdf(url, page),
website-app-1  |     ^^^^^^^^^^^^^^^^^^^^^
website-app-1  |   File "/app/apps/common/receipt.py", line 93, in render_pdf
website-app-1  |     pdf = loop.run_until_complete(to_pdf())
website-app-1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
website-app-1  |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
website-app-1  |     return future.result()
website-app-1  |            ^^^^^^^^^^^^^^^
website-app-1  |   File "/app/apps/common/receipt.py", line 66, in to_pdf
website-app-1  |     browser = await launch(
website-app-1  |               ^^^^^^^^^^^^^
website-app-1  |   File "/root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.11/lib/python3.11/site-packages/pyppeteer/launcher.py", line 307, in launch
website-app-1  |     return await Launcher(options, **kwargs).launch()
website-app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
website-app-1  |   File "/root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.11/lib/python3.11/site-packages/pyppeteer/launcher.py", line 168, in launch
website-app-1  |     self.browserWSEndpoint = get_ws_endpoint(self.url)
website-app-1  |                              ^^^^^^^^^^^^^^^^^^^^^^^^^
website-app-1  |   File "/root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.11/lib/python3.11/site-packages/pyppeteer/launcher.py", line 227, in get_ws_endpoint
website-app-1  |     raise BrowserError('Browser closed unexpectedly:\n')
website-app-1  | pyppeteer.errors.BrowserError: Browser closed unexpectedly:
```

</details>

**Comment by marksteward** [comment]
Result (someone has been trying to generate their receipt directly this evening):

```
root     3820229 3820142  0 18:21 ?        00:00:20 /root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.11/bin/python /root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.11/bin/gunicorn -k gthread -c gunicorn.py -w 6 -b 0.0.0.0:8000 --preload wsgi:app
root     3826757 3820229  0 19:38 ?        00:00:00 [chrome] <defunct>
root     3826798 3820229  0 19:39 ?        00:00:00 [chrome] <defunct>
root     3826805 3820229  0 19:39 ?        00:00:00 [chrome] <defunct>
root     3836081 3820229  0 21:22 ?        00:00:00 [chrome] <defunct>
root     3836086 3820229  0 21:22 ?        00:00:00 [chrome] <defunct>
root     3836127 3820229  0 21:23 ?        00:00:00 [chrome] <defunct>
root     3837321 3820229  0 21:35 ?        00:00:00 [chrome] <defunct>
root     3837398 3820229  0 21:35 ?        00:00:00 [chrome] <defunct>
...
root     3820230 3820142  0 18:21 ?        00:00:28 /root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.11/bin/python /root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.11/bin/gunicorn -k gthread -c gunicorn.py -w 6 -b 0.0.0.0:8000 --preload wsgi:app
root     3824042 3820230  0 19:04 ?        00:00:00 [chrome] <defunct>
root     3824080 3820230  0 19:05 ?        00:00:00 [chrome] <defunct>
root     3824083 3820230  0 19:05 ?        00:00:00 [chrome] <defunct>
root     3837324 3820230  0 21:35 ?        00:00:00 [chrome] <defunct>
```

It seems to try multiple times before giving up, and does block other requests while this is happening.
