### ISSUE TITLE
Non-Ticket purchases cannot be transferred

### ISSUE THREAD

**Issue by russss** [emfcamp/Website#1451]
I made the badge products transferrable, but transfers are failing:

```
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.11/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.11/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.11/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/apps/tickets/__init__.py", line 122, in transfer
    assert ticket.owner_id == current_user.id
           ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'owner_id'
```

**Comment by russss** [comment]
This is because the transfer flow is looking for Tickets and a badge is not a Ticket
