### ISSUE TITLE
Catch/cope with invalid emails during signup

### ISSUE THREAD

**Issue by marksteward** [emfcamp/Website#335]
```
2016-03-21_21:45:30.41820 2016-03-21 21:45:30,418 3619 INFO Anon apps.payments.banktransfer Created bank payment 950 (...)
2016-03-21_21:45:31.17640 2016-03-21 21:45:31,171 3619 ERROR Anon main Exception on /tickets/pay [POST]
2016-03-21_21:45:31.17643 Traceback (most recent call last):
2016-03-21_21:45:31.17644   File "/var/www/www.emfcamp.org/env/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
2016-03-21_21:45:31.17645     response = self.full_dispatch_request()
2016-03-21_21:45:31.17646   File "/var/www/www.emfcamp.org/env/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
2016-03-21_21:45:31.17647     rv = self.handle_user_exception(e)
2016-03-21_21:45:31.17648   File "/var/www/www.emfcamp.org/env/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
2016-03-21_21:45:31.17649     reraise(exc_type, exc_value, tb)
2016-03-21_21:45:31.17650   File "/var/www/www.emfcamp.org/env/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
2016-03-21_21:45:31.17651     rv = self.dispatch_request()
2016-03-21_21:45:31.17652   File "/var/www/www.emfcamp.org/env/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
2016-03-21_21:45:31.17653     return self.view_functions[rule.endpoint](**req.view_args)
2016-03-21_21:45:31.17654   File "/var/www/www.emfcamp.org/apps/tickets.py", line 288, in pay
2016-03-21_21:45:31.17655     return transfer_start(payment)
2016-03-21_21:45:31.17658   File "/var/www/www.emfcamp.org/apps/payments/banktransfer.py", line 32, in transfer_start
2016-03-21_21:45:31.17659     mail.send(msg)
2016-03-21_21:45:31.17660   File "/var/www/www.emfcamp.org/env/local/lib/python2.7/site-packages/flask_mail.py", line 492, in send
2016-03-21_21:45:31.17660     message.send(connection)
2016-03-21_21:45:31.17661   File "/var/www/www.emfcamp.org/env/local/lib/python2.7/site-packages/flask_mail.py", line 427, in send
2016-03-21_21:45:31.17662     connection.send(self)
2016-03-21_21:45:31.17665   File "/var/www/www.emfcamp.org/env/local/lib/python2.7/site-packages/flask_mail.py", line 192, in send
2016-03-21_21:45:31.17666     message.rcpt_options)
2016-03-21_21:45:31.17667   File "/usr/lib/python2.7/smtplib.py", line 742, in sendmail
2016-03-21_21:45:31.17668     raise SMTPRecipientsRefused(senderrs)
2016-03-21_21:45:31.17669 SMTPRecipientsRefused: {u'...': (450, '4.1.2 <...>: Recipient address rejected: Domain not found')}
```

**Comment by marksteward** [comment]
See #432.
