### ISSUE TITLE
500s on cfp-review list page when all submissions have been reviewed

### ISSUE THREAD

**Issue by SamLR** [emfcamp/Website#670]
Apparently `cfp-review/review` will 500 if there are no submissions remaining to be reviewed (reported by Tim Brown)

**Comment by marksteward** [comment]
It's this:

```
Jun 08 12:29:11 maxwell pipenv[10383]: Traceback (most recent call last):
Jun 08 12:29:11 maxwell pipenv[10383]:   File "/var/www/www.emfcamp.org/.venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
Jun 08 12:29:11 maxwell pipenv[10383]:     response = self.full_dispatch_request()
Jun 08 12:29:11 maxwell pipenv[10383]:   File "/var/www/www.emfcamp.org/.venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
Jun 08 12:29:11 maxwell pipenv[10383]:     rv = self.handle_user_exception(e)
Jun 08 12:29:11 maxwell pipenv[10383]:   File "/var/www/www.emfcamp.org/.venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
Jun 08 12:29:11 maxwell pipenv[10383]:     reraise(exc_type, exc_value, tb)
Jun 08 12:29:11 maxwell pipenv[10383]:   File "/var/www/www.emfcamp.org/.venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
Jun 08 12:29:11 maxwell pipenv[10383]:     raise value
Jun 08 12:29:11 maxwell pipenv[10383]:   File "/var/www/www.emfcamp.org/.venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
Jun 08 12:29:11 maxwell pipenv[10383]:     rv = self.dispatch_request()
Jun 08 12:29:11 maxwell pipenv[10383]:   File "/var/www/www.emfcamp.org/.venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
Jun 08 12:29:11 maxwell pipenv[10383]:     return self.view_functions[rule.endpoint](**req.view_args)
Jun 08 12:29:11 maxwell pipenv[10383]:   File "<decorator-gen-52>", line 2, in review_list
Jun 08 12:29:11 maxwell pipenv[10383]:   File "/var/www/www.emfcamp.org/apps/common/__init__.py", line 200, in call
Jun 08 12:29:11 maxwell pipenv[10383]:     return f(*args, **kwargs)
Jun 08 12:29:11 maxwell pipenv[10383]:   File "/var/www/www.emfcamp.org/apps/cfp_review.py", line 786, in review_list
Jun 08 12:29:11 maxwell pipenv[10383]:     reviewed = [p for o, p in sorted(reviewed, reverse=True)]
Jun 08 12:29:11 maxwell pipenv[10383]: TypeError: unorderable types: NoneType() < int()
```

**Comment by marksteward** [comment]
Which happens when you choose either recuse or blocked without first voting (pretty likely).
