### ISSUE TITLE
Attempting to sign up for a role from the role info page errors if you're already signed up.

### ISSUE THREAD

**Issue by idnorton** [emfcamp/Website#933]
Steps to reproduce:

1. View roles list (http://0.0.0.0:5000/volunteer/choose-roles)
2. Select More at the end of the description to see more details
3. Click the `Sign up for this role` button (you need to have `VOLUNTEERS_SCHEDULE` enabled in your config to see this)
4. Repeat steps 2 and 3 signing up for the same role.

```
sqlalchemy.exc.IntegrityError
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "pk_volunteer_role_interest"
DETAIL:  Key (volunteer_id, role_id)=(1, 9) already exists.

[SQL: INSERT INTO volunteer_role_interest (volunteer_id, role_id) VALUES (%(volunteer_id)s, %(role_id)s)]
[parameters: {'volunteer_id': 1, 'role_id': 9, 'operation_type': 0}]
(Background on this error at: http://sqlalche.me/e/gkpj)

Traceback (most recent call last)
File "/root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.7/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1284, in _execute_context
cursor, statement, parameters, context
File "/root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.7/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
cursor.execute(statement, parameters)
The above exception was the direct cause of the following exception:
File "/root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.7/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
return self.wsgi_app(environ, start_response)
File "/root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.7/lib/python3.7/site-packages/werkzeug/local.py", line 230, in application
return ClosingIterator(app(environ, start_response), self.cleanup)
File "/root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.7/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
response = self.handle_exception(e)
File "/root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.7/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
return original_handler(e)
File "/root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
return cors_after_request(app.make_response(f(*args, **kwargs)))
File "/root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.7/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
reraise(exc_type, exc_value, tb)
File "/root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.7/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
return original_handler(e)
File "/root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
return cors_after_request(app.make_response(f(*args, **kwargs)))
File "/root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.7/lib/python3.7/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
return view_func(**req.view_args)
File "<decorator-gen-105>", line 2, in role
 
File "/app/apps/common/__init__.py", line 195, in call
return f(*args, **kw)
File "<decorator-gen-104>", line 2, in role
 
File "/app/apps/common/__init__.py", line 219, in call
return f(*args, **kwargs)
File "/app/apps/volunteer/choose_roles.py", line 98, in role
db.session.commit()
File "/root/.cache/pypoetry/virtualenvs/website-9TtSrW0h-py3.7/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 163, in do
return getattr(self.registry(), name)(*args, **kwargs)
```

**Comment by idnorton** [comment]
Logical actions seem to be one of:

1. Inform the user they're signed up for the role and no button to sign up again
2. Offer to remove yourself from this role if you're already signed up

**Comment by idnorton** [comment]
This is still an outstanding issue.

**Comment by anorthall** [comment]
Happy to have a go at this.
